# Generated by Django 4.0.4 on 2022-04-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField()),
                ('wing', models.PositiveSmallIntegerField()),
                ('occupy', models.TextField(max_length=99)),
            ],
        ),
    ]
