# Generated by Django 4.0.4 on 2022-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Washer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='washingmachine',
            name='occupied_at',
            field=models.TimeField(default=None),
        ),
    ]
