# Generated by Django 4.0.4 on 2022-04-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Washer', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='idntn',
        ),
    ]
