# Generated by Django 4.0.4 on 2022-04-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Washer', '0004_remove_student_idntn'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='I',
            field=models.CharField(default='', max_length=9),
        ),
    ]
